/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.shuntian.portlet.intranet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BasicInformation service. Represents a row in the &quot;Intranet_BasicInformation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.shuntian.portlet.intranet.model.impl.BasicInformationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.shuntian.portlet.intranet.model.impl.BasicInformationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BasicInformation
 * @see com.shuntian.portlet.intranet.model.impl.BasicInformationImpl
 * @see com.shuntian.portlet.intranet.model.impl.BasicInformationModelImpl
 * @generated
 */
public interface BasicInformationModel extends BaseModel<BasicInformation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a basic information model instance should use the {@link BasicInformation} interface instead.
	 */

	/**
	 * Returns the primary key of this basic information.
	 *
	 * @return the primary key of this basic information
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this basic information.
	 *
	 * @param primaryKey the primary key of this basic information
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this basic information.
	 *
	 * @return the ID of this basic information
	 */
	public long getId();

	/**
	 * Sets the ID of this basic information.
	 *
	 * @param id the ID of this basic information
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this basic information.
	 *
	 * @return the user ID of this basic information
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this basic information.
	 *
	 * @param userId the user ID of this basic information
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this basic information.
	 *
	 * @return the user uuid of this basic information
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this basic information.
	 *
	 * @param userUuid the user uuid of this basic information
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the name of this basic information.
	 *
	 * @return the name of this basic information
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this basic information.
	 *
	 * @param name the name of this basic information
	 */
	public void setName(String name);

	/**
	 * Returns the sex of this basic information.
	 *
	 * @return the sex of this basic information
	 */
	public int getSex();

	/**
	 * Sets the sex of this basic information.
	 *
	 * @param sex the sex of this basic information
	 */
	public void setSex(int sex);

	/**
	 * Returns the id number of this basic information.
	 *
	 * @return the id number of this basic information
	 */
	@AutoEscape
	public String getIdNumber();

	/**
	 * Sets the id number of this basic information.
	 *
	 * @param idNumber the id number of this basic information
	 */
	public void setIdNumber(String idNumber);

	/**
	 * Returns the nation of this basic information.
	 *
	 * @return the nation of this basic information
	 */
	@AutoEscape
	public String getNation();

	/**
	 * Sets the nation of this basic information.
	 *
	 * @param nation the nation of this basic information
	 */
	public void setNation(String nation);

	/**
	 * Returns the place of origin of this basic information.
	 *
	 * @return the place of origin of this basic information
	 */
	@AutoEscape
	public String getPlaceOfOrigin();

	/**
	 * Sets the place of origin of this basic information.
	 *
	 * @param placeOfOrigin the place of origin of this basic information
	 */
	public void setPlaceOfOrigin(String placeOfOrigin);

	/**
	 * Returns the account properties of this basic information.
	 *
	 * @return the account properties of this basic information
	 */
	@AutoEscape
	public String getAccountProperties();

	/**
	 * Sets the account properties of this basic information.
	 *
	 * @param accountProperties the account properties of this basic information
	 */
	public void setAccountProperties(String accountProperties);

	/**
	 * Returns the birth date of this basic information.
	 *
	 * @return the birth date of this basic information
	 */
	public Date getBirthDate();

	/**
	 * Sets the birth date of this basic information.
	 *
	 * @param birthDate the birth date of this basic information
	 */
	public void setBirthDate(Date birthDate);

	/**
	 * Returns the marital status of this basic information.
	 *
	 * @return the marital status of this basic information
	 */
	@AutoEscape
	public String getMaritalStatus();

	/**
	 * Sets the marital status of this basic information.
	 *
	 * @param maritalStatus the marital status of this basic information
	 */
	public void setMaritalStatus(String maritalStatus);

	/**
	 * Returns the highest degree of this basic information.
	 *
	 * @return the highest degree of this basic information
	 */
	@AutoEscape
	public String getHighestDegree();

	/**
	 * Sets the highest degree of this basic information.
	 *
	 * @param highestDegree the highest degree of this basic information
	 */
	public void setHighestDegree(String highestDegree);

	/**
	 * Returns the political background of this basic information.
	 *
	 * @return the political background of this basic information
	 */
	@AutoEscape
	public String getPoliticalBackground();

	/**
	 * Sets the political background of this basic information.
	 *
	 * @param politicalBackground the political background of this basic information
	 */
	public void setPoliticalBackground(String politicalBackground);

	/**
	 * Returns the file location of this basic information.
	 *
	 * @return the file location of this basic information
	 */
	@AutoEscape
	public String getFileLocation();

	/**
	 * Sets the file location of this basic information.
	 *
	 * @param fileLocation the file location of this basic information
	 */
	public void setFileLocation(String fileLocation);

	/**
	 * Returns the base pay of this basic information.
	 *
	 * @return the base pay of this basic information
	 */
	public double getBasePay();

	/**
	 * Sets the base pay of this basic information.
	 *
	 * @param basePay the base pay of this basic information
	 */
	public void setBasePay(double basePay);

	/**
	 * Returns the performance pay of this basic information.
	 *
	 * @return the performance pay of this basic information
	 */
	public double getPerformancePay();

	/**
	 * Sets the performance pay of this basic information.
	 *
	 * @param performancePay the performance pay of this basic information
	 */
	public void setPerformancePay(double performancePay);

	/**
	 * Returns the health of this basic information.
	 *
	 * @return the health of this basic information
	 */
	@AutoEscape
	public String getHealth();

	/**
	 * Sets the health of this basic information.
	 *
	 * @param health the health of this basic information
	 */
	public void setHealth(String health);

	/**
	 * Returns the contact phone of this basic information.
	 *
	 * @return the contact phone of this basic information
	 */
	@AutoEscape
	public String getContactPhone();

	/**
	 * Sets the contact phone of this basic information.
	 *
	 * @param contactPhone the contact phone of this basic information
	 */
	public void setContactPhone(String contactPhone);

	/**
	 * Returns the mail of this basic information.
	 *
	 * @return the mail of this basic information
	 */
	@AutoEscape
	public String getMail();

	/**
	 * Sets the mail of this basic information.
	 *
	 * @param mail the mail of this basic information
	 */
	public void setMail(String mail);

	/**
	 * Returns the domicile of this basic information.
	 *
	 * @return the domicile of this basic information
	 */
	@AutoEscape
	public String getDomicile();

	/**
	 * Sets the domicile of this basic information.
	 *
	 * @param domicile the domicile of this basic information
	 */
	public void setDomicile(String domicile);

	/**
	 * Returns the residence phone of this basic information.
	 *
	 * @return the residence phone of this basic information
	 */
	@AutoEscape
	public String getResidencePhone();

	/**
	 * Sets the residence phone of this basic information.
	 *
	 * @param residencePhone the residence phone of this basic information
	 */
	public void setResidencePhone(String residencePhone);

	/**
	 * Returns the current residential address of this basic information.
	 *
	 * @return the current residential address of this basic information
	 */
	@AutoEscape
	public String getCurrentResidentialAddress();

	/**
	 * Sets the current residential address of this basic information.
	 *
	 * @param currentResidentialAddress the current residential address of this basic information
	 */
	public void setCurrentResidentialAddress(String currentResidentialAddress);

	/**
	 * Returns the current residential address phone of this basic information.
	 *
	 * @return the current residential address phone of this basic information
	 */
	@AutoEscape
	public String getCurrentResidentialAddressPhone();

	/**
	 * Sets the current residential address phone of this basic information.
	 *
	 * @param currentResidentialAddressPhone the current residential address phone of this basic information
	 */
	public void setCurrentResidentialAddressPhone(
		String currentResidentialAddressPhone);

	/**
	 * Returns the emergency contact of this basic information.
	 *
	 * @return the emergency contact of this basic information
	 */
	@AutoEscape
	public String getEmergencyContact();

	/**
	 * Sets the emergency contact of this basic information.
	 *
	 * @param emergencyContact the emergency contact of this basic information
	 */
	public void setEmergencyContact(String emergencyContact);

	/**
	 * Returns the emergency contact relation of this basic information.
	 *
	 * @return the emergency contact relation of this basic information
	 */
	@AutoEscape
	public String getEmergencyContactRelation();

	/**
	 * Sets the emergency contact relation of this basic information.
	 *
	 * @param emergencyContactRelation the emergency contact relation of this basic information
	 */
	public void setEmergencyContactRelation(String emergencyContactRelation);

	/**
	 * Returns the emergency contact phone of this basic information.
	 *
	 * @return the emergency contact phone of this basic information
	 */
	@AutoEscape
	public String getEmergencyContactPhone();

	/**
	 * Sets the emergency contact phone of this basic information.
	 *
	 * @param emergencyContactPhone the emergency contact phone of this basic information
	 */
	public void setEmergencyContactPhone(String emergencyContactPhone);

	/**
	 * Returns the is leave of this basic information.
	 *
	 * @return the is leave of this basic information
	 */
	public int getIsLeave();

	/**
	 * Sets the is leave of this basic information.
	 *
	 * @param isLeave the is leave of this basic information
	 */
	public void setIsLeave(int isLeave);

	/**
	 * Returns the department ID of this basic information.
	 *
	 * @return the department ID of this basic information
	 */
	public long getDepartmentId();

	/**
	 * Sets the department ID of this basic information.
	 *
	 * @param departmentId the department ID of this basic information
	 */
	public void setDepartmentId(long departmentId);

	/**
	 * Returns the create user ID of this basic information.
	 *
	 * @return the create user ID of this basic information
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this basic information.
	 *
	 * @param createUserId the create user ID of this basic information
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this basic information.
	 *
	 * @return the create user uuid of this basic information
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreateUserUuid() throws SystemException;

	/**
	 * Sets the create user uuid of this basic information.
	 *
	 * @param createUserUuid the create user uuid of this basic information
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the create date of this basic information.
	 *
	 * @return the create date of this basic information
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this basic information.
	 *
	 * @param createDate the create date of this basic information
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified user ID of this basic information.
	 *
	 * @return the modified user ID of this basic information
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this basic information.
	 *
	 * @param modifiedUserId the modified user ID of this basic information
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this basic information.
	 *
	 * @return the modified user uuid of this basic information
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this basic information.
	 *
	 * @param modifiedUserUuid the modified user uuid of this basic information
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the modified date of this basic information.
	 *
	 * @return the modified date of this basic information
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this basic information.
	 *
	 * @param modifiedDate the modified date of this basic information
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BasicInformation basicInformation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BasicInformation> toCacheModel();

	@Override
	public BasicInformation toEscapedModel();

	@Override
	public BasicInformation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}