/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.shuntian.portlet.intranet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Department service. Represents a row in the &quot;Intranet_Department&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.shuntian.portlet.intranet.model.impl.DepartmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.shuntian.portlet.intranet.model.impl.DepartmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Department
 * @see com.shuntian.portlet.intranet.model.impl.DepartmentImpl
 * @see com.shuntian.portlet.intranet.model.impl.DepartmentModelImpl
 * @generated
 */
public interface DepartmentModel extends BaseModel<Department> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a department model instance should use the {@link Department} interface instead.
	 */

	/**
	 * Returns the primary key of this department.
	 *
	 * @return the primary key of this department
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this department.
	 *
	 * @param primaryKey the primary key of this department
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this department.
	 *
	 * @return the ID of this department
	 */
	public long getId();

	/**
	 * Sets the ID of this department.
	 *
	 * @param id the ID of this department
	 */
	public void setId(long id);

	/**
	 * Returns the name of this department.
	 *
	 * @return the name of this department
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this department.
	 *
	 * @param name the name of this department
	 */
	public void setName(String name);

	/**
	 * Returns the leader of this department.
	 *
	 * @return the leader of this department
	 */
	public long getLeader();

	/**
	 * Sets the leader of this department.
	 *
	 * @param leader the leader of this department
	 */
	public void setLeader(long leader);

	/**
	 * Returns the create user ID of this department.
	 *
	 * @return the create user ID of this department
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this department.
	 *
	 * @param createUserId the create user ID of this department
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this department.
	 *
	 * @return the create user uuid of this department
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreateUserUuid() throws SystemException;

	/**
	 * Sets the create user uuid of this department.
	 *
	 * @param createUserUuid the create user uuid of this department
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the create date of this department.
	 *
	 * @return the create date of this department
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this department.
	 *
	 * @param createDate the create date of this department
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified user ID of this department.
	 *
	 * @return the modified user ID of this department
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this department.
	 *
	 * @param modifiedUserId the modified user ID of this department
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this department.
	 *
	 * @return the modified user uuid of this department
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this department.
	 *
	 * @param modifiedUserUuid the modified user uuid of this department
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the modified date of this department.
	 *
	 * @return the modified date of this department
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this department.
	 *
	 * @param modifiedDate the modified date of this department
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Department department);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Department> toCacheModel();

	@Override
	public Department toEscapedModel();

	@Override
	public Department toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}