/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.shuntian.portlet.intranet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Education service. Represents a row in the &quot;Intranet_Education&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.shuntian.portlet.intranet.model.impl.EducationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.shuntian.portlet.intranet.model.impl.EducationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Education
 * @see com.shuntian.portlet.intranet.model.impl.EducationImpl
 * @see com.shuntian.portlet.intranet.model.impl.EducationModelImpl
 * @generated
 */
public interface EducationModel extends BaseModel<Education> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a education model instance should use the {@link Education} interface instead.
	 */

	/**
	 * Returns the primary key of this education.
	 *
	 * @return the primary key of this education
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this education.
	 *
	 * @param primaryKey the primary key of this education
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this education.
	 *
	 * @return the ID of this education
	 */
	public long getId();

	/**
	 * Sets the ID of this education.
	 *
	 * @param id the ID of this education
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this education.
	 *
	 * @return the user ID of this education
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this education.
	 *
	 * @param userId the user ID of this education
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this education.
	 *
	 * @return the user uuid of this education
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this education.
	 *
	 * @param userUuid the user uuid of this education
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the e witness of this education.
	 *
	 * @return the e witness of this education
	 */
	@AutoEscape
	public String getEWitness();

	/**
	 * Sets the e witness of this education.
	 *
	 * @param eWitness the e witness of this education
	 */
	public void setEWitness(String eWitness);

	/**
	 * Returns the e professional of this education.
	 *
	 * @return the e professional of this education
	 */
	@AutoEscape
	public String getEProfessional();

	/**
	 * Sets the e professional of this education.
	 *
	 * @param eProfessional the e professional of this education
	 */
	public void setEProfessional(String eProfessional);

	/**
	 * Returns the e university of this education.
	 *
	 * @return the e university of this education
	 */
	@AutoEscape
	public String getEUniversity();

	/**
	 * Sets the e university of this education.
	 *
	 * @param eUniversity the e university of this education
	 */
	public void setEUniversity(String eUniversity);

	/**
	 * Returns the e contact phone of this education.
	 *
	 * @return the e contact phone of this education
	 */
	@AutoEscape
	public String getEContactPhone();

	/**
	 * Sets the e contact phone of this education.
	 *
	 * @param eContactPhone the e contact phone of this education
	 */
	public void setEContactPhone(String eContactPhone);

	/**
	 * Returns the e start time year of this education.
	 *
	 * @return the e start time year of this education
	 */
	@AutoEscape
	public String getEStartTimeYear();

	/**
	 * Sets the e start time year of this education.
	 *
	 * @param eStartTimeYear the e start time year of this education
	 */
	public void setEStartTimeYear(String eStartTimeYear);

	/**
	 * Returns the e start time month of this education.
	 *
	 * @return the e start time month of this education
	 */
	@AutoEscape
	public String getEStartTimeMonth();

	/**
	 * Sets the e start time month of this education.
	 *
	 * @param eStartTimeMonth the e start time month of this education
	 */
	public void setEStartTimeMonth(String eStartTimeMonth);

	/**
	 * Returns the e stop time year of this education.
	 *
	 * @return the e stop time year of this education
	 */
	@AutoEscape
	public String getEStopTimeYear();

	/**
	 * Sets the e stop time year of this education.
	 *
	 * @param eStopTimeYear the e stop time year of this education
	 */
	public void setEStopTimeYear(String eStopTimeYear);

	/**
	 * Returns the e stop time month of this education.
	 *
	 * @return the e stop time month of this education
	 */
	@AutoEscape
	public String getEStopTimeMonth();

	/**
	 * Sets the e stop time month of this education.
	 *
	 * @param eStopTimeMonth the e stop time month of this education
	 */
	public void setEStopTimeMonth(String eStopTimeMonth);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Education education);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Education> toCacheModel();

	@Override
	public Education toEscapedModel();

	@Override
	public Education toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}