/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.shuntian.portlet.intranet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ExtInformation service. Represents a row in the &quot;Intranet_ExtInformation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.shuntian.portlet.intranet.model.impl.ExtInformationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.shuntian.portlet.intranet.model.impl.ExtInformationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExtInformation
 * @see com.shuntian.portlet.intranet.model.impl.ExtInformationImpl
 * @see com.shuntian.portlet.intranet.model.impl.ExtInformationModelImpl
 * @generated
 */
public interface ExtInformationModel extends BaseModel<ExtInformation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ext information model instance should use the {@link ExtInformation} interface instead.
	 */

	/**
	 * Returns the primary key of this ext information.
	 *
	 * @return the primary key of this ext information
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ext information.
	 *
	 * @param primaryKey the primary key of this ext information
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this ext information.
	 *
	 * @return the ID of this ext information
	 */
	public long getId();

	/**
	 * Sets the ID of this ext information.
	 *
	 * @param id the ID of this ext information
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this ext information.
	 *
	 * @return the user ID of this ext information
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this ext information.
	 *
	 * @param userId the user ID of this ext information
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ext information.
	 *
	 * @return the user uuid of this ext information
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this ext information.
	 *
	 * @param userUuid the user uuid of this ext information
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the open city of this ext information.
	 *
	 * @return the open city of this ext information
	 */
	@AutoEscape
	public String getOpenCity();

	/**
	 * Sets the open city of this ext information.
	 *
	 * @param openCity the open city of this ext information
	 */
	public void setOpenCity(String openCity);

	/**
	 * Returns the bank name of this ext information.
	 *
	 * @return the bank name of this ext information
	 */
	@AutoEscape
	public String getBankName();

	/**
	 * Sets the bank name of this ext information.
	 *
	 * @param bankName the bank name of this ext information
	 */
	public void setBankName(String bankName);

	/**
	 * Returns the bank ID of this ext information.
	 *
	 * @return the bank ID of this ext information
	 */
	@AutoEscape
	public String getBankId();

	/**
	 * Sets the bank ID of this ext information.
	 *
	 * @param bankId the bank ID of this ext information
	 */
	public void setBankId(String bankId);

	/**
	 * Returns the labor contract start of this ext information.
	 *
	 * @return the labor contract start of this ext information
	 */
	public Date getLaborContractStart();

	/**
	 * Sets the labor contract start of this ext information.
	 *
	 * @param laborContractStart the labor contract start of this ext information
	 */
	public void setLaborContractStart(Date laborContractStart);

	/**
	 * Returns the labor contract end of this ext information.
	 *
	 * @return the labor contract end of this ext information
	 */
	public Date getLaborContractEnd();

	/**
	 * Sets the labor contract end of this ext information.
	 *
	 * @param laborContractEnd the labor contract end of this ext information
	 */
	public void setLaborContractEnd(Date laborContractEnd);

	/**
	 * Returns the probation period start of this ext information.
	 *
	 * @return the probation period start of this ext information
	 */
	public Date getProbationPeriodStart();

	/**
	 * Sets the probation period start of this ext information.
	 *
	 * @param probationPeriodStart the probation period start of this ext information
	 */
	public void setProbationPeriodStart(Date probationPeriodStart);

	/**
	 * Returns the probation period end of this ext information.
	 *
	 * @return the probation period end of this ext information
	 */
	public Date getProbationPeriodEnd();

	/**
	 * Sets the probation period end of this ext information.
	 *
	 * @param probationPeriodEnd the probation period end of this ext information
	 */
	public void setProbationPeriodEnd(Date probationPeriodEnd);

	/**
	 * Returns the indured location of this ext information.
	 *
	 * @return the indured location of this ext information
	 */
	@AutoEscape
	public String getInduredLocation();

	/**
	 * Sets the indured location of this ext information.
	 *
	 * @param induredLocation the indured location of this ext information
	 */
	public void setInduredLocation(String induredLocation);

	/**
	 * Returns the frist insured of this ext information.
	 *
	 * @return the frist insured of this ext information
	 */
	public Date getFristInsured();

	/**
	 * Sets the frist insured of this ext information.
	 *
	 * @param fristInsured the frist insured of this ext information
	 */
	public void setFristInsured(Date fristInsured);

	/**
	 * Returns the is insured of this ext information.
	 *
	 * @return the is insured of this ext information
	 */
	@AutoEscape
	public String getIsInsured();

	/**
	 * Sets the is insured of this ext information.
	 *
	 * @param isInsured the is insured of this ext information
	 */
	public void setIsInsured(String isInsured);

	/**
	 * Returns the create user ID of this ext information.
	 *
	 * @return the create user ID of this ext information
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this ext information.
	 *
	 * @param createUserId the create user ID of this ext information
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this ext information.
	 *
	 * @return the create user uuid of this ext information
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreateUserUuid() throws SystemException;

	/**
	 * Sets the create user uuid of this ext information.
	 *
	 * @param createUserUuid the create user uuid of this ext information
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the create date of this ext information.
	 *
	 * @return the create date of this ext information
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this ext information.
	 *
	 * @param createDate the create date of this ext information
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified user ID of this ext information.
	 *
	 * @return the modified user ID of this ext information
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this ext information.
	 *
	 * @param modifiedUserId the modified user ID of this ext information
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this ext information.
	 *
	 * @return the modified user uuid of this ext information
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this ext information.
	 *
	 * @param modifiedUserUuid the modified user uuid of this ext information
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the modified date of this ext information.
	 *
	 * @return the modified date of this ext information
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ext information.
	 *
	 * @param modifiedDate the modified date of this ext information
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ExtInformation extInformation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ExtInformation> toCacheModel();

	@Override
	public ExtInformation toEscapedModel();

	@Override
	public ExtInformation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}