/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.shuntian.portlet.intranet.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Overtime service. Represents a row in the &quot;Intranet_Overtime&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.shuntian.portlet.intranet.model.impl.OvertimeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.shuntian.portlet.intranet.model.impl.OvertimeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Overtime
 * @see com.shuntian.portlet.intranet.model.impl.OvertimeImpl
 * @see com.shuntian.portlet.intranet.model.impl.OvertimeModelImpl
 * @generated
 */
public interface OvertimeModel extends BaseModel<Overtime> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a overtime model instance should use the {@link Overtime} interface instead.
	 */

	/**
	 * Returns the primary key of this overtime.
	 *
	 * @return the primary key of this overtime
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this overtime.
	 *
	 * @param primaryKey the primary key of this overtime
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this overtime.
	 *
	 * @return the ID of this overtime
	 */
	public long getId();

	/**
	 * Sets the ID of this overtime.
	 *
	 * @param id the ID of this overtime
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this overtime.
	 *
	 * @return the user ID of this overtime
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this overtime.
	 *
	 * @param userId the user ID of this overtime
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this overtime.
	 *
	 * @return the user uuid of this overtime
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this overtime.
	 *
	 * @param userUuid the user uuid of this overtime
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the usually overtime of this overtime.
	 *
	 * @return the usually overtime of this overtime
	 */
	public double getUsuallyOvertime();

	/**
	 * Sets the usually overtime of this overtime.
	 *
	 * @param usuallyOvertime the usually overtime of this overtime
	 */
	public void setUsuallyOvertime(double usuallyOvertime);

	/**
	 * Returns the rest overtime of this overtime.
	 *
	 * @return the rest overtime of this overtime
	 */
	public double getRestOvertime();

	/**
	 * Sets the rest overtime of this overtime.
	 *
	 * @param restOvertime the rest overtime of this overtime
	 */
	public void setRestOvertime(double restOvertime);

	/**
	 * Returns the legal overtime of this overtime.
	 *
	 * @return the legal overtime of this overtime
	 */
	public double getLegalOvertime();

	/**
	 * Sets the legal overtime of this overtime.
	 *
	 * @param legalOvertime the legal overtime of this overtime
	 */
	public void setLegalOvertime(double legalOvertime);

	/**
	 * Returns the overtime monthly of this overtime.
	 *
	 * @return the overtime monthly of this overtime
	 */
	public long getOvertimeMonthly();

	/**
	 * Sets the overtime monthly of this overtime.
	 *
	 * @param overtimeMonthly the overtime monthly of this overtime
	 */
	public void setOvertimeMonthly(long overtimeMonthly);

	/**
	 * Returns the create user ID of this overtime.
	 *
	 * @return the create user ID of this overtime
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this overtime.
	 *
	 * @param createUserId the create user ID of this overtime
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this overtime.
	 *
	 * @return the create user uuid of this overtime
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreateUserUuid() throws SystemException;

	/**
	 * Sets the create user uuid of this overtime.
	 *
	 * @param createUserUuid the create user uuid of this overtime
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the create date of this overtime.
	 *
	 * @return the create date of this overtime
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this overtime.
	 *
	 * @param createDate the create date of this overtime
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified user ID of this overtime.
	 *
	 * @return the modified user ID of this overtime
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this overtime.
	 *
	 * @param modifiedUserId the modified user ID of this overtime
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this overtime.
	 *
	 * @return the modified user uuid of this overtime
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this overtime.
	 *
	 * @param modifiedUserUuid the modified user uuid of this overtime
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the modified date of this overtime.
	 *
	 * @return the modified date of this overtime
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this overtime.
	 *
	 * @param modifiedDate the modified date of this overtime
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Overtime overtime);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Overtime> toCacheModel();

	@Override
	public Overtime toEscapedModel();

	@Override
	public Overtime toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}