/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.shuntian.portlet.intranet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WorkExperience service. Represents a row in the &quot;Intranet_WorkExperience&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.shuntian.portlet.intranet.model.impl.WorkExperienceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.shuntian.portlet.intranet.model.impl.WorkExperienceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WorkExperience
 * @see com.shuntian.portlet.intranet.model.impl.WorkExperienceImpl
 * @see com.shuntian.portlet.intranet.model.impl.WorkExperienceModelImpl
 * @generated
 */
public interface WorkExperienceModel extends BaseModel<WorkExperience> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a work experience model instance should use the {@link WorkExperience} interface instead.
	 */

	/**
	 * Returns the primary key of this work experience.
	 *
	 * @return the primary key of this work experience
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this work experience.
	 *
	 * @param primaryKey the primary key of this work experience
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this work experience.
	 *
	 * @return the ID of this work experience
	 */
	public long getId();

	/**
	 * Sets the ID of this work experience.
	 *
	 * @param id the ID of this work experience
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this work experience.
	 *
	 * @return the user ID of this work experience
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this work experience.
	 *
	 * @param userId the user ID of this work experience
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this work experience.
	 *
	 * @return the user uuid of this work experience
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this work experience.
	 *
	 * @param userUuid the user uuid of this work experience
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the witness of this work experience.
	 *
	 * @return the witness of this work experience
	 */
	@AutoEscape
	public String getWitness();

	/**
	 * Sets the witness of this work experience.
	 *
	 * @param witness the witness of this work experience
	 */
	public void setWitness(String witness);

	/**
	 * Returns the once job of this work experience.
	 *
	 * @return the once job of this work experience
	 */
	@AutoEscape
	public String getOnceJob();

	/**
	 * Sets the once job of this work experience.
	 *
	 * @param onceJob the once job of this work experience
	 */
	public void setOnceJob(String onceJob);

	/**
	 * Returns the work unit of this work experience.
	 *
	 * @return the work unit of this work experience
	 */
	@AutoEscape
	public String getWorkUnit();

	/**
	 * Sets the work unit of this work experience.
	 *
	 * @param workUnit the work unit of this work experience
	 */
	public void setWorkUnit(String workUnit);

	/**
	 * Returns the contact phone of this work experience.
	 *
	 * @return the contact phone of this work experience
	 */
	@AutoEscape
	public String getContactPhone();

	/**
	 * Sets the contact phone of this work experience.
	 *
	 * @param contactPhone the contact phone of this work experience
	 */
	public void setContactPhone(String contactPhone);

	/**
	 * Returns the start time of this work experience.
	 *
	 * @return the start time of this work experience
	 */
	public Date getStartTime();

	/**
	 * Sets the start time of this work experience.
	 *
	 * @param startTime the start time of this work experience
	 */
	public void setStartTime(Date startTime);

	/**
	 * Returns the stop time of this work experience.
	 *
	 * @return the stop time of this work experience
	 */
	public Date getStopTime();

	/**
	 * Sets the stop time of this work experience.
	 *
	 * @param stopTime the stop time of this work experience
	 */
	public void setStopTime(Date stopTime);

	/**
	 * Returns the create user ID of this work experience.
	 *
	 * @return the create user ID of this work experience
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this work experience.
	 *
	 * @param createUserId the create user ID of this work experience
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this work experience.
	 *
	 * @return the create user uuid of this work experience
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreateUserUuid() throws SystemException;

	/**
	 * Sets the create user uuid of this work experience.
	 *
	 * @param createUserUuid the create user uuid of this work experience
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the create date of this work experience.
	 *
	 * @return the create date of this work experience
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this work experience.
	 *
	 * @param createDate the create date of this work experience
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified user ID of this work experience.
	 *
	 * @return the modified user ID of this work experience
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this work experience.
	 *
	 * @param modifiedUserId the modified user ID of this work experience
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this work experience.
	 *
	 * @return the modified user uuid of this work experience
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this work experience.
	 *
	 * @param modifiedUserUuid the modified user uuid of this work experience
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the modified date of this work experience.
	 *
	 * @return the modified date of this work experience
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this work experience.
	 *
	 * @param modifiedDate the modified date of this work experience
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(WorkExperience workExperience);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WorkExperience> toCacheModel();

	@Override
	public WorkExperience toEscapedModel();

	@Override
	public WorkExperience toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}