/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.shuntian.portlet.intranet.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.shuntian.portlet.intranet.model.Overtime;
import com.shuntian.portlet.intranet.service.OvertimeLocalServiceUtil;

/**
 * The extended model base implementation for the Overtime service. Represents a row in the &quot;Intranet_Overtime&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OvertimeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OvertimeImpl
 * @see com.shuntian.portlet.intranet.model.Overtime
 * @generated
 */
public abstract class OvertimeBaseImpl extends OvertimeModelImpl
	implements Overtime {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a overtime model instance should use the {@link Overtime} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			OvertimeLocalServiceUtil.addOvertime(this);
		}
		else {
			OvertimeLocalServiceUtil.updateOvertime(this);
		}
	}
}